DenemeBlog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import IndexView, PostView, SearchView

app_name = "blog"

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('search/', SearchView.as_view(), name="search"),
    path('<slug:slug>/', PostView.as_view(), name="post"),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext as _


class Post(models.Model):
    title = models.CharField(_("Title"), max_length=255)
    slug = models.SlugField(_("Slug"), null=True, blank=True, unique=True)
    draft = models.BooleanField(_("Is Draft"), default=True)
    thumb = models.ImageField(_("Thumbnail"), upload_to="thumbs/")
    keywords = models.CharField(_("Keywords"), max_length=2048, null=True, blank=True)
    date = models.DateTimeField(_("Publish Date"), null=True, blank=True)
    content = models.TextField(_("Content"))

    class Meta:
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")
        ordering = ["-date"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.draft and not self.date:
            self.date = timezone.now()
        if not self.slug:
            temp_slug = slugify(self.title)
            in_slug = temp_slug
            add_num = None
            while True:
                if add_num:
                    in_slug = temp.slug + str(add_num)
                try:
                    is_slug = self.__class__.objects.get(slug=in_slug)
                except Exception:
                    is_slug = None
                if not is_slug:
                    self.slug = in_slug
                    break
                elif is_slug and add_num:
                    add_num += 1
                else:
                    add_num = 1
                continue
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:post', args=[str(self.slug)])

blog/views.py
from django.db.models import Q
from django.views.generic import ListView, DetailView
from blog.models import Post


def get_qs():
    return Post.objects.filter(draft=False)


class IndexView(ListView):
    template_name = "index.html"
    context_object_name = "posts"

    def get_queryset(self):
        return get_qs()


class SearchView(IndexView):

    def get_queryset(self):
        q = self.request.GET.get("q")
        return get_qs().filter(
                    Q(title__icontains=q) |
                    Q(keywords__icontains=q) |
                    Q(content__icontains=q)
               )


class PostView(DetailView):
    model = Post
    template_name = "post.html"
    context_object_name = "post"
    slug_field = "slug"

templates/base.html
{% load static %}

<html>
    <head>
        <title>{% block title %}{% endblock %}DenemeBlog</title>
        <meta charsheet="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
        <div class="container">
            {% include "partials/nav.html" %}
            {% block header %}
            {% endblock header %}
            <div class="col-md-10 offset-md-1">
                {% block body %}
                {% endblock body %}
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load markdown %}

{% block body %}
<div class="row">
    {% for post in posts %}
    <div class="col-lg-4">
        <div class="card">
            <a href="{{ post.get_absolute_url }}">
                <img src="{{ post.thumb.url }}" class="card-img-top" alt="{{ post.title }}">
            </a>
          <div class="card-body">
            <a href="{{ post.get_absolute_url }}">
              <h5 class="card-title">{{ post.title }}</h5>
            </a>
              <p class="card-text">{{ post.content|render_md|truncatechars_html:50 }}</p>
          </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock body %}

templates/partials/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Deneme Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Anasayfa</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'blog:search' %}">
      <input class="form-control mr-sm-2" name="q" type="search" placeholder="Ara..." aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Ara</button>
    </form>
  </div>
</nav>

templates/post.html
{% extends "base.html" %}
{% load markdown %}

{% block title %}{{ post.title }}{% endblock title %}

{% block header %}
<div class="card">
    <a href="{{ post.thumb.url }}" target="_blank">
        <img src="{{ post.thumb.url }}" class="card-img-top" alt="{{ post.title }}">
    </a>
</div>
{% endblock header %}

{% block body %}
    <h1>{{ post.title }}</h1>
    <p><small class="post-date">{{ post.date|date }}</small></p>
    <div class="post-body">{{ post.content|render_md }}</div>
{% endblock body %}